### ISSUE TITLE
把这个错误，师傅知道怎么解决吗？

### ISSUE THREAD

**Issue by gancc6** [y1nglamore/IDOR_detect_tool#3]
[+] 启动mitmproxy 127.0.0.1:8889
in script addons.py: 'type' object is not subscriptable
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<ErrorCheck._shutdown_if_errored() done, defined at /usr/local/lib/python3.8/site-packages/mitmproxy/addons/errorcheck.py:18> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.13_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.8/3.8.13_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/local/Cellar/python@3.8/3.8.13_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/local/Cellar/python@3.8/3.8.13_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/local/Cellar/python@3.8/3.8.13_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/addons/errorcheck.py", line 20, in _shutdown_if_errored
    sys.exit(1)
SystemExit: 1

**Comment by y1nglamore** [comment]
我猜的可能是config的问题，因为addons.py中只有这里取了下标
https://github.com/y1nglamore/IDOR_detect_tool/blob/456adc7c8f85bbe730a4ba525f58f98503bcfb98/addons.py#L27

可以尝试debug以下，或者输出`self.config`看下config的解析是否正常，正常情况下`self.config`是一个这样格式的字典：
https://github.com/y1nglamore/IDOR_detect_tool/blob/456adc7c8f85bbe730a4ba525f58f98503bcfb98/config/config.py#L17-L21

**Comment by gancc6** [comment]
错误在这个

from core.replay import Replay

我注释掉代码正常使用 不知道有没有影响

**Comment by gancc6** [comment]
python3.8
macos

**Comment by y1nglamore** [comment]
我没有get到具体哪句代码出了问题，但是Replay模块不用的话就没法重放和判断漏洞了

**Comment by y1nglamore** [comment]
原因出在了`mrs: list[dict]`
https://github.com/y1nglamore/IDOR_detect_tool/blob/e017206087447671c3a0d2cb3185ccfd3ef7f48e/core/replay.py#L68

这个语法在python 3.9以下不支持，现已修复

![m1-170525_s0ZCU6](http://cdn2.pic.y1ng.vip/uPic/2023/02/03/m1-170525_s0ZCU6.png)
![m1-170538_OzvG9t](http://cdn2.pic.y1ng.vip/uPic/2023/02/03/m1-170538_OzvG9t.png)
